const {chromium, devices} = require(process.env.PLAYWRIGHT_MODULE || '/usr/local/lib/node_modules/playwright');
const fs = require('node:fs'); const assert = require('node:assert/strict');
const base = process.env.TEST_URL || 'http://127.0.0.1:4174';
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const checks=[],errors=[]; const dir='qa';
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const page=await context.newPage(); page.on('pageerror', e=>errors.push(e.message));
 await page.goto(base,{waitUntil:'networkidle'});
 assert.equal(await page.locator('h1').count(),1);
 for(const id of ['aegis','optima']){
  const gap=await page.locator(`#${id}`).evaluate(el=>el.querySelector('.project-eyebrow').getBoundingClientRect().top-el.querySelector('h2').getBoundingClientRect().bottom);
  assert(gap>=10,`${id} gap ${gap}`);
 }
 checks.push('Aegis/Optima title line-height and description clearance >=10px');
 const originals=['hero','aegis','optima','about'];
 for(const name of originals) assert(await page.locator(`img[src$="/art/${name}.webp"]`).evaluate(e=>e.complete&&e.naturalWidth>0));
 checks.push('All four unchanged approved artwork images load');
 await page.screenshot({path:`${dir}/desktop-hero.png`});
 await page.locator('#aegis').scrollIntoViewIfNeeded(); await page.screenshot({path:`${dir}/desktop-aegis.png`});
 await page.getByRole('button',{name:'Learn more about Aegis'}).click();
 assert(await page.locator('dialog[open]').isVisible());
 await page.getByRole('tab',{name:'Workflow',exact:true}).click();
 assert(await page.locator('dialog').getByText('Understand',{exact:true}).isVisible());
 await page.getByRole('tab',{name:'Direction',exact:true}).click(); assert(await page.getByText('Where it is heading',{exact:true}).isVisible());
 await page.getByRole('tab',{name:'Overview',exact:true}).focus(); await page.keyboard.press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:'Workflow',exact:true}).getAttribute('aria-selected'),'true');
 await page.screenshot({path:`${dir}/desktop-project-panel.png`});
 for(let i=0;i<16;i++) { await page.keyboard.press('Tab'); assert(await page.evaluate(()=>!!document.activeElement.closest('dialog'))); }
 await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog[open]').count(),0);
 assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Learn more about Aegis');
 checks.push('Project details, three tabs, arrow-key switching, focus trapping, Escape and focus restoration');
 await page.getByRole('button',{name:'Learn more about Optima'}).click();
 assert(await page.getByRole('link',{name:/Explore the public lab/}).isVisible());
 await page.getByRole('button',{name:/Talk about Optima/}).click();
 assert.equal(await page.locator('select[name="topic"]').inputValue(),'Optima');
 checks.push('Project-to-contact transition preselects correct subject');
 await page.getByRole('button',{name:'Close panel',exact:true}).click();
 await page.getByRole('button',{name:/Meet the builder/}).click();
 assert(await page.getByText(/Industrial Engineering/).isVisible()); await page.keyboard.press('Escape');
 checks.push('Founder story is reachable and detailed');
 await page.getByRole('button',{name:/Start a conversation/}).click();
 let requests=0; let payload;
 await page.route('https://formsubmit.co/ajax/**',async route=>{requests++;payload=route.request().postDataJSON(); await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:'true',message:'Accepted'})});});
 await page.getByRole('button',{name:'Send message',exact:true}).click(); assert.equal(requests,0);
 await page.locator('input[name="name"]').fill('Website QA');await page.locator('input[name="email"]').fill('qa@example.com');await page.locator('textarea[name="message"]').fill('This is an intercepted automated test. Do not send it.');
 await page.locator('input[name="consent"]').check();await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.form-feedback').textContent.includes('accepted'));
 assert.equal(requests,1);assert.equal(payload._honey,'');assert.equal(payload.email,'qa@example.com');assert(await page.getByRole('button',{name:'Accepted by service',exact:true}).isDisabled());
 checks.push('Contact success simulated only: required fields, consent, single submit, explicit service acceptance');
 await page.getByRole('button',{name:'Close panel',exact:true}).click(); await page.unrouteAll();
 await page.getByRole('button',{name:/Start a conversation/}).click();
 await page.route('https://formsubmit.co/ajax/**',route=>route.fulfill({status:403,contentType:'application/json',body:'{}'}));
 await page.locator('input[name="name"]').fill('Website QA');await page.locator('input[name="email"]').fill('qa@example.com');await page.locator('textarea[name="message"]').fill('Keep this draft after a rejected request.');await page.locator('input[name="consent"]').check();await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.form-feedback').textContent.includes('could not accept'));
 assert.equal(await page.locator('textarea[name="message"]').inputValue(),'Keep this draft after a rejected request.');
 await page.screenshot({path:`${dir}/desktop-contact-panel.png`});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Close panel',exact:true}).click();await page.unrouteAll();
 checks.push('Contact rejection preserves draft and never claims delivery');
 await page.locator('#questions').scrollIntoViewIfNeeded();await page.locator('summary').first().click();assert(await page.getByText(/Both are active development projects/).isVisible());
 checks.push('Native FAQ opens without a framework or network request');
 await page.locator('#contact').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/desktop-contact.png`});
 assert.equal(await page.getByRole('link',{name:/GitHub: ttvzicotix/}).getAttribute('href'),'https://github.com/ttvzicotix');
 const logo=await page.request.get(`${base}/brand/zicotix-logo-white-transparent.png`);assert.equal(logo.status(),200);
 checks.push('Public GitHub link and downloadable PNG resolve');
 for(const width of [320,375,390,430,760,768,1024,1440,1920]){
  await page.setViewportSize({width,height:900}); await page.evaluate(()=>window.scrollTo(0,0)); await page.waitForTimeout(70);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert(!overflow,`overflow ${width}`);
  await page.getByRole('button',{name:'Learn more about Optima'}).click();
  assert(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`dialog overflow ${width}`);
  const closeBox=await page.getByRole('button',{name:'Close panel'}).boundingBox();assert(closeBox.width>=44&&closeBox.height>=44);
  await page.keyboard.press('Escape');
 }
 checks.push('No page or project-dialog horizontal overflow at 320/375/390/430/760/768/1024/1440/1920px; 44px close targets');
 const mobile=await browser.newContext({...devices['iPhone 13'],reducedMotion:'reduce'}); const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));
 await mp.goto(base,{waitUntil:'networkidle'});await mp.screenshot({path:`${dir}/mobile-hero.png`});
 await mp.getByRole('button',{name:'Open navigation'}).tap();await mp.locator('#primary-links').getByRole('link',{name:'Optima',exact:true}).tap();
 assert.equal(await mp.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'false');
 await mp.getByRole('button',{name:'Learn more about Optima'}).tap(); await mp.screenshot({path:`${dir}/mobile-project-panel.png`});
 await mp.getByRole('button',{name:'Close panel'}).tap();await mp.getByRole('button',{name:/Start a conversation/}).tap();
 assert.equal(await mp.locator('input[name="email"]').evaluate(e=>getComputedStyle(e).fontSize),'16px');
 await mp.screenshot({path:`${dir}/mobile-contact-panel.png`});
 await mp.getByRole('button',{name:'Close panel'}).tap(); await mp.locator('#aegis').scrollIntoViewIfNeeded();await mp.screenshot({path:`${dir}/mobile-aegis.png`});
 checks.push('iPhone 13 emulation: touch menu, project panel, contact panel, 16px form inputs; reduced-motion static fallback');
 const rainPage=await browser.newPage({viewport:{width:1440,height:900}});await rainPage.goto(base,{waitUntil:'networkidle'});await rainPage.waitForSelector('canvas');
 await rainPage.getByRole('button',{name:/Pause atmosphere/}).click();assert.equal(await rainPage.locator('.hero').getAttribute('data-paused'),'true');
 await rainPage.getByRole('button',{name:/Resume atmosphere/}).click();
 checks.push('WebGL rain remains present and pause/resume still works');
 await browser.close();assert.deepEqual(errors,[]);
 const result={passed:true,checks,errors,contactEndToEnd:'NOT VERIFIED: simulated response tests only; one real setup POST was blocked with HTTP 403',mobileScope:'Chromium touch/device emulation, not physical iPhone Safari',testedAt:new Date().toISOString()};
 fs.writeFileSync('qa/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
